// Central manifest of every sprite the game expects. BootScene loads each
// from /assets/sprites/<key>.png if it exists (generated by
// @hive/gemini-art); anything missing gets a procedurally-drawn
// placeholder so the game always looks like a game, even before
// the real atlas is generated.

export const UNIT_SPRITE_KEYS = [
  'unit-WorkerAnt',
  'unit-SoldierAnt',
  'unit-DirtDigger',
  'unit-Forager',
  'unit-Wasp',
  'unit-HoneyTank',
  'unit-ShieldBeetle',
  'unit-BombBeetle',
  'unit-Roller',
  'unit-Jumper',
  'unit-WebSetter',
  'unit-Ambusher',
] as const;

export const BUILDING_SPRITE_KEYS = [
  'building-QueenChamber',
  'building-DewCollector',
  'building-MushroomTurret',
  'building-LeafWall',
  'building-PebbleBunker',
  'building-LarvaNursery',
  'building-SugarVault',
  'building-TunnelJunction',
  'building-DungeonTrap',
] as const;

export const UI_SPRITE_KEYS = [
  'ui-resource-sugar',
  'ui-resource-leaf',
  'ui-resource-milk',
  'ui-button-primary',
  'ui-button-secondary',
] as const;

export const ALL_SPRITE_KEYS = [
  ...UNIT_SPRITE_KEYS,
  ...BUILDING_SPRITE_KEYS,
  ...UI_SPRITE_KEYS,
] as const;

export type SpriteKey = (typeof ALL_SPRITE_KEYS)[number];

// Canonical on-disk path for a sprite. Kept in one place so the
// BootScene loader and tooling agree.
export function spritePath(key: string): string {
  return `assets/sprites/${key}.png`;
}
