// Central manifest of every sprite the game expects. BootScene loads each
// from /assets/sprites/<key>.png if it exists (generated by
// @hive/gemini-art); anything missing gets a procedurally-drawn
// placeholder so the game always looks like a game, even before
// the real atlas is generated.

export const UNIT_SPRITE_KEYS = [
  'unit-WorkerAnt',
  'unit-SoldierAnt',
  'unit-DirtDigger',
  'unit-Forager',
  'unit-Wasp',
  'unit-HoneyTank',
  'unit-ShieldBeetle',
  'unit-BombBeetle',
  'unit-Roller',
  'unit-Jumper',
  'unit-WebSetter',
  'unit-Ambusher',
] as const;

export const BUILDING_SPRITE_KEYS = [
  'building-QueenChamber',
  'building-DewCollector',
  'building-MushroomTurret',
  'building-LeafWall',
  'building-PebbleBunker',
  'building-LarvaNursery',
  'building-SugarVault',
  'building-TunnelJunction',
  'building-DungeonTrap',
] as const;

export const UI_SPRITE_KEYS = [
  'ui-resource-sugar',
  'ui-resource-leaf',
  'ui-resource-milk',
  'ui-button-primary',
  'ui-button-secondary',
] as const;

// Units that have a walk-cycle spritesheet available. The on-disk
// file lives at /assets/sprites/unit-<Kind>-walk.{webp,png} and is a
// 2-frame horizontal strip (256×128 total, 128×128 per frame). Kept
// in sync with the walkCycles bucket in tools/gemini-art/prompts.json
// and with ANIMATED_UNIT_KINDS on the server.
//
// Why 2 frames instead of more: asking Gemini for a single multi-pose
// strip gave near-identical frames (the model spreads attention across
// the whole image). Two separate single-subject calls, one per pose,
// produce dramatically more leg-position variation — enough that the
// walk reads as an actual walk. See admin/main.ts generateWalkCycle.
export const ANIMATED_UNIT_KINDS = ['WorkerAnt', 'SoldierAnt', 'Wasp'] as const;
export type AnimatedUnitKind = (typeof ANIMATED_UNIT_KINDS)[number];

export const WALK_CYCLE_SPRITE_KEYS = ANIMATED_UNIT_KINDS.map(
  (k) => `unit-${k}-walk`,
) as ReadonlyArray<string>;

// Spritesheet geometry. Keep it a single source of truth so BootScene
// loader, anim definitions, and scene sprite sizing can't drift.
export const WALK_CYCLE_FRAME_W = 128;
export const WALK_CYCLE_FRAME_H = 128;
export const WALK_CYCLE_FRAME_COUNT = 2;
// 2 frames × 6 fps = 3 full pose swaps per second, which reads as a
// brisk walk without looking choppy. Bumping higher makes the legs
// look frantic at the small in-game sprite scale.
export const WALK_CYCLE_FPS = 6;

export const ALL_SPRITE_KEYS = [
  ...UNIT_SPRITE_KEYS,
  ...BUILDING_SPRITE_KEYS,
  ...UI_SPRITE_KEYS,
] as const;

export type SpriteKey = (typeof ALL_SPRITE_KEYS)[number];

// Canonical on-disk path for a sprite. Kept in one place so the
// BootScene loader and tooling agree.
export function spritePath(key: string): string {
  return `assets/sprites/${key}.png`;
}
