// Admin audio API. Sits next to /admin/api/* sprite routes and shares
// the same bearer-auth hook (registerAdminHook in auth/adminAuth.ts).
//
// The audio pipeline mirrors the sprite one:
//   * Prompts live in tools/audio-gen/audio-prompts.json (committable).
//   * Generated bytes land in client/public/audio/<key>.mp3 (mirrored
//     into client/dist/assets-style if the build dir exists), and the
//     manifest at client/public/audio/manifest.json is rewritten so
//     the runtime audioAssets.ts loader picks them up.
//   * Each entry has a kind ('sfx' | 'music') so the admin UI knows
//     whether to expose a duration knob in seconds (sfx) or
//     milliseconds × scene-length (music).
//
// /admin/api/audio/generate returns a 502 with a clear "key not
// configured" message when ELEVENLABS_API_KEY is unset (via the
// elevenlabs.ts client); the prompt-config + delete routes stay
// usable without a key so the operator can curate prompts and clean
// up old files even before the credential is set.

import type { FastifyInstance } from 'fastify';
import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, stat, writeFile, unlink } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  elevenLabsConfigured,
  generateMusic,
  generateSfx,
} from '../admin/elevenlabs.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..', '..', '..');

const PUBLIC_AUDIO_DIR = join(REPO_ROOT, 'client', 'public', 'audio');
const DIST_AUDIO_DIR = join(REPO_ROOT, 'client', 'dist', 'audio');
const PROMPTS_PATH = join(REPO_ROOT, 'tools', 'audio-gen', 'audio-prompts.json');
const MANIFEST_PATH = join(PUBLIC_AUDIO_DIR, 'manifest.json');

// Keys are short stable identifiers — same shape as sprite keys so the
// validation can stay identical.
const ALLOWED_KEY_RE = /^[a-z0-9][a-z0-9-_]{1,63}$/i;
const DANGEROUS_KEYS = new Set(['__proto__', 'prototype', 'constructor']);
const MAX_PROMPT_BYTES = 4096;
const MAX_AUDIO_BYTES = 15 * 1024 * 1024; // 15 MB — well above any 5-minute mp3.

function sanitizeKey(key: string): string | null {
  if (DANGEROUS_KEYS.has(key)) return null;
  return ALLOWED_KEY_RE.test(key) ? key : null;
}

export type AudioKind = 'sfx' | 'music';

interface AudioPromptEntry {
  // Free-text prompt sent to ElevenLabs. Trimmed; up to MAX_PROMPT_BYTES.
  prompt: string;
  // Categorises the entry — controls which ElevenLabs endpoint we hit
  // and which duration knob the admin UI shows.
  kind: AudioKind;
  // Optional seconds (sfx) — clamped 0.5..22 server-side.
  durationSeconds?: number;
  // Optional milliseconds (music) — clamped 10000..300000 server-side.
  durationMs?: number;
  // Optional 0..1, sfx-only. Higher = stricter prompt adherence.
  promptInfluence?: number;
  // Optional 0..1 master gain applied at playback time. Mirrors the
  // sprite manifest's `gain` field; defaults to 0.7 in audioAssets.ts.
  gain?: number;
  // Free-text label shown in the admin UI. Useful when one key has
  // several "moods" tracked over time.
  label?: string;
  // Per-key kill switch. When false, the manifest entry is removed
  // (the .mp3 stays on disk so the admin can re-enable later) and the
  // runtime falls back to its synth body for SFX or to the procedural
  // pad for music. Default true when the field is missing.
  enabled?: boolean;
}

type AudioPromptsFile = Record<string, AudioPromptEntry>;

// Distinct error so the caller can refuse to overwrite a corrupted
// prompts file. If we silently returned an empty object on a JSON
// parse error, the next PUT would `writePrompts({})` and erase the
// committed defaults — a quiet data-loss footgun.
class AudioPromptsParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'AudioPromptsParseError';
  }
}

async function readPrompts(): Promise<AudioPromptsFile> {
  let raw: string;
  try {
    raw = await readFile(PROMPTS_PATH, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      // Genuinely missing file — first run, return an empty bucket so
      // the admin can start adding entries.
      return Object.create(null) as AudioPromptsFile;
    }
    throw err;
  }
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      // Strip any prototype-pollution attempts from the on-disk file.
      const out: AudioPromptsFile = Object.create(null) as AudioPromptsFile;
      for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
        if (DANGEROUS_KEYS.has(k)) continue;
        if (!ALLOWED_KEY_RE.test(k)) continue;
        if (!v || typeof v !== 'object') continue;
        const e = v as Partial<AudioPromptEntry>;
        if (typeof e.prompt !== 'string') continue;
        if (e.kind !== 'sfx' && e.kind !== 'music') continue;
        out[k] = {
          prompt: e.prompt,
          kind: e.kind,
          ...(typeof e.durationSeconds === 'number' && { durationSeconds: e.durationSeconds }),
          ...(typeof e.durationMs === 'number' && { durationMs: e.durationMs }),
          ...(typeof e.promptInfluence === 'number' && { promptInfluence: e.promptInfluence }),
          ...(typeof e.gain === 'number' && { gain: e.gain }),
          ...(typeof e.label === 'string' && { label: e.label }),
          ...(typeof e.enabled === 'boolean' && { enabled: e.enabled }),
        };
      }
      return out;
    }
    // Top-level shape isn't an object → treat as malformed.
    throw new AudioPromptsParseError(
      'audio-prompts.json must be a JSON object keyed by audio key',
    );
  } catch (err) {
    if (err instanceof AudioPromptsParseError) throw err;
    // SyntaxError from JSON.parse falls through here — surface it
    // rather than silently returning {}, which would let the next PUT
    // overwrite a recoverable file with an empty one.
    throw new AudioPromptsParseError(
      `audio-prompts.json is malformed: ${(err as Error).message}`,
    );
  }
}

async function writePrompts(prompts: AudioPromptsFile): Promise<void> {
  await mkdir(dirname(PROMPTS_PATH), { recursive: true });
  await writeFile(PROMPTS_PATH, JSON.stringify(prompts, null, 2) + '\n', 'utf8');
}

interface ManifestEntry {
  key: string;
  src: string;
  gain?: number;
}

async function readManifest(): Promise<ManifestEntry[]> {
  try {
    const raw = await readFile(MANIFEST_PATH, 'utf8');
    const parsed = JSON.parse(raw) as unknown;
    if (Array.isArray(parsed)) {
      return parsed.filter(
        (e): e is ManifestEntry =>
          !!e &&
          typeof e === 'object' &&
          typeof (e as ManifestEntry).key === 'string' &&
          typeof (e as ManifestEntry).src === 'string',
      );
    }
  } catch {
    // missing → empty
  }
  return [];
}

async function writeManifest(entries: ManifestEntry[]): Promise<void> {
  await mkdir(PUBLIC_AUDIO_DIR, { recursive: true });
  await writeFile(MANIFEST_PATH, JSON.stringify(entries, null, 2) + '\n', 'utf8');
}

// Make the served manifest reflect the prompt entry's enabled flag.
// Adds or replaces the entry when the file exists on disk and the
// prompt is enabled (default); removes it when disabled or when the
// audio file isn't on disk yet. Idempotent — only writes when the
// manifest actually changes so we don't churn fastify-static's mtimes.
async function reconcileManifestForKey(
  key: string,
  entry: AudioPromptEntry,
): Promise<void> {
  const manifest = await readManifest();
  const idx = manifest.findIndex((e) => e.key === key);

  // Resolve which file backs this key. mp3 is the canonical output of
  // the ElevenLabs save handler; .wav is also tolerated for back-compat
  // with anything synth-generated by tools/audio-gen.
  let src: string | null = null;
  for (const ext of ['mp3', 'wav']) {
    try {
      await stat(join(PUBLIC_AUDIO_DIR, `${key}.${ext}`));
      src = `${key}.${ext}`;
      break;
    } catch {
      // not there
    }
  }

  const wantEntry = src !== null && entry.enabled !== false;
  if (!wantEntry) {
    if (idx >= 0) {
      manifest.splice(idx, 1);
      await writeManifest(manifest);
    }
    return;
  }
  const next: ManifestEntry = {
    key,
    src: src!,
    ...(typeof entry.gain === 'number' ? { gain: entry.gain } : {}),
  };
  if (idx >= 0) {
    const cur = manifest[idx]!;
    if (cur.src === next.src && cur.gain === next.gain) return;
    manifest[idx] = next;
  } else {
    manifest.push(next);
  }
  await writeManifest(manifest);
}

async function mirrorAudioToDisk(
  key: string,
  bytes: Buffer,
): Promise<{ path: string; mirroredToDist: boolean }> {
  const filename = `${key}.mp3`;
  await mkdir(PUBLIC_AUDIO_DIR, { recursive: true });
  await writeFile(join(PUBLIC_AUDIO_DIR, filename), bytes);
  let mirroredToDist = false;
  if (existsSync(join(REPO_ROOT, 'client', 'dist'))) {
    try {
      await mkdir(DIST_AUDIO_DIR, { recursive: true });
      await writeFile(join(DIST_AUDIO_DIR, filename), bytes);
      mirroredToDist = true;
    } catch {
      // best-effort
    }
  }
  return { path: `/audio/${filename}`, mirroredToDist };
}

interface FileMeta {
  key: string;
  filename: string;
  size: number;
  mtime: number;
}

async function listAudioFiles(): Promise<FileMeta[]> {
  const out: FileMeta[] = [];
  try {
    const names = await readdir(PUBLIC_AUDIO_DIR);
    for (const n of names) {
      if (!n.endsWith('.mp3') && !n.endsWith('.wav')) continue;
      try {
        const s = await stat(join(PUBLIC_AUDIO_DIR, n));
        const key = n.replace(/\.(mp3|wav)$/i, '');
        out.push({ key, filename: n, size: s.size, mtime: s.mtimeMs });
      } catch {
        // file disappeared mid-listing
      }
    }
  } catch {
    // dir doesn't exist yet
  }
  return out;
}

interface UpsertPromptBody {
  key: string;
  entry: AudioPromptEntry;
}

interface GenerateBody {
  key: string;
  // Override the on-disk prompt for a single ad-hoc generation. If omitted
  // the server reads the prompt from audio-prompts.json[key].
  prompt?: string;
  kind?: AudioKind;
  durationSeconds?: number;
  durationMs?: number;
  promptInfluence?: number;
}

interface SaveBody {
  key: string;
  data: string; // base64 mp3
  // Optional gain override stored in the manifest. Defaults to whatever
  // is set on the prompt entry, falling back to 0.7 at runtime.
  gain?: number;
}

export function registerAdminAudio(app: FastifyInstance): void {
  // Combined status: prompt config, on-disk files, manifest, and the
  // ElevenLabs configuration flag so the UI can show a banner when the
  // key is missing.
  app.get('/admin/api/audio/status', async (_req, reply) => {
    let prompts: AudioPromptsFile;
    try {
      prompts = await readPrompts();
    } catch (err) {
      // Surface a parse error explicitly rather than blanking the
      // admin UI — the operator can SSH in and fix the JSON instead
      // of staring at an empty grid wondering where everything went.
      app.log.error({ err }, 'failed to read audio-prompts.json');
      reply.code(500);
      return { error: (err as Error).message };
    }
    const [files, manifest] = await Promise.all([
      listAudioFiles(),
      readManifest(),
    ]);
    return {
      elevenLabsConfigured: elevenLabsConfigured(),
      audioDir: PUBLIC_AUDIO_DIR,
      prompts,
      files,
      manifest,
    };
  });

  app.put<{ Body: UpsertPromptBody }>(
    '/admin/api/audio/prompts',
    async (req, reply) => {
      const body = req.body;
      if (!body || typeof body.key !== 'string' || !body.entry) {
        reply.code(400);
        return { error: 'key + entry required' };
      }
      const safeKey = sanitizeKey(body.key);
      if (!safeKey) {
        reply.code(400);
        return { error: 'key must match [a-z0-9][a-z0-9-_]{1,63}' };
      }
      const e = body.entry;
      if (typeof e.prompt !== 'string' || e.prompt.length > MAX_PROMPT_BYTES) {
        reply.code(400);
        return { error: `prompt required, ≤${MAX_PROMPT_BYTES} chars` };
      }
      if (e.kind !== 'sfx' && e.kind !== 'music') {
        reply.code(400);
        return { error: 'kind must be "sfx" or "music"' };
      }
      const sanitized: AudioPromptEntry = {
        prompt: e.prompt,
        kind: e.kind,
      };
      if (typeof e.durationSeconds === 'number' && Number.isFinite(e.durationSeconds)) {
        sanitized.durationSeconds = Math.max(0.5, Math.min(22, e.durationSeconds));
      }
      if (typeof e.durationMs === 'number' && Number.isFinite(e.durationMs)) {
        sanitized.durationMs = Math.max(10000, Math.min(300000, Math.floor(e.durationMs)));
      }
      if (typeof e.promptInfluence === 'number' && Number.isFinite(e.promptInfluence)) {
        sanitized.promptInfluence = Math.max(0, Math.min(1, e.promptInfluence));
      }
      if (typeof e.gain === 'number' && Number.isFinite(e.gain)) {
        sanitized.gain = Math.max(0, Math.min(1, e.gain));
      }
      if (typeof e.label === 'string' && e.label.trim() !== '') {
        sanitized.label = e.label.trim().slice(0, 120);
      }
      if (typeof e.enabled === 'boolean') {
        sanitized.enabled = e.enabled;
      }

      const prompts = await readPrompts();
      // Object.defineProperty avoids __proto__ shenanigans even though
      // the key has already passed the regex.
      Object.defineProperty(prompts, safeKey, {
        value: sanitized,
        writable: true,
        enumerable: true,
        configurable: true,
      });
      await writePrompts(prompts);
      // Reconcile the manifest so a flipped `enabled` immediately
      // adds/removes the entry without requiring a re-save of the audio.
      await reconcileManifestForKey(safeKey, sanitized);
      return { ok: true, key: safeKey, entry: sanitized };
    },
  );

  // Quick toggle endpoint — flips just `enabled` without requiring the
  // admin UI to round-trip the full prompt entry. Updates both the
  // prompt config and the served manifest in one call.
  app.patch<{ Body: { enabled: boolean } }>(
    '/admin/api/audio/prompts/:key/enabled',
    async (req, reply) => {
      const params = req.params as { key: string };
      const safeKey = sanitizeKey(params.key);
      if (!safeKey) {
        reply.code(400);
        return { error: 'invalid key' };
      }
      const enabled = req.body?.enabled;
      if (typeof enabled !== 'boolean') {
        reply.code(400);
        return { error: 'body.enabled must be boolean' };
      }
      const prompts = await readPrompts();
      const existing = prompts[safeKey];
      if (!existing) {
        reply.code(404);
        return { error: `no prompt configured for "${safeKey}"` };
      }
      const next: AudioPromptEntry = { ...existing, enabled };
      Object.defineProperty(prompts, safeKey, {
        value: next,
        writable: true,
        enumerable: true,
        configurable: true,
      });
      await writePrompts(prompts);
      await reconcileManifestForKey(safeKey, next);
      return { ok: true, key: safeKey, enabled };
    },
  );

  app.delete('/admin/api/audio/prompts/:key', async (req, reply) => {
    const params = req.params as { key: string };
    const safeKey = sanitizeKey(params.key);
    if (!safeKey) {
      reply.code(400);
      return { error: 'invalid key' };
    }
    const prompts = await readPrompts();
    if (!Object.prototype.hasOwnProperty.call(prompts, safeKey)) {
      return { ok: true, removed: false };
    }
    delete prompts[safeKey];
    await writePrompts(prompts);
    return { ok: true, removed: true };
  });

  app.post<{ Body: GenerateBody }>(
    '/admin/api/audio/generate',
    async (req, reply) => {
      const body = req.body;
      if (!body || typeof body.key !== 'string') {
        reply.code(400);
        return { error: 'key required' };
      }
      const safeKey = sanitizeKey(body.key);
      if (!safeKey) {
        reply.code(400);
        return { error: 'key must match [a-z0-9][a-z0-9-_]{1,63}' };
      }
      const prompts = await readPrompts();
      const stored = prompts[safeKey];
      const prompt = (body.prompt ?? stored?.prompt ?? '').trim();
      const kind: AudioKind =
        body.kind ?? stored?.kind ?? (safeKey.startsWith('music-') ? 'music' : 'sfx');
      if (prompt === '') {
        reply.code(400);
        return { error: 'prompt required (set one in the admin UI or pass it inline)' };
      }
      try {
        let audio;
        if (kind === 'music') {
          audio = await generateMusic({
            prompt,
            ...(body.durationMs !== undefined
              ? { durationMs: body.durationMs }
              : stored?.durationMs !== undefined
                ? { durationMs: stored.durationMs }
                : {}),
          });
        } else {
          audio = await generateSfx({
            prompt,
            ...(body.durationSeconds !== undefined
              ? { durationSeconds: body.durationSeconds }
              : stored?.durationSeconds !== undefined
                ? { durationSeconds: stored.durationSeconds }
                : {}),
            ...(body.promptInfluence !== undefined
              ? { promptInfluence: body.promptInfluence }
              : stored?.promptInfluence !== undefined
                ? { promptInfluence: stored.promptInfluence }
                : {}),
          });
        }
        return { audio, kind, key: safeKey };
      } catch (err) {
        reply.code(502);
        return { error: (err as Error).message };
      }
    },
  );

  // Route-level bodyLimit: a 5-minute mp3 maxes around 6 MB binary →
  // ~8 MB base64, plus JSON envelope. 22 MB has comfortable headroom
  // and stays scoped to this single endpoint instead of widening the
  // global DoS surface.
  app.post<{ Body: SaveBody }>('/admin/api/audio/save', { bodyLimit: 22_000_000 }, async (req, reply) => {
    const body = req.body;
    if (!body || !body.key || !body.data) {
      reply.code(400);
      return { error: 'key + data required' };
    }
    const safeKey = sanitizeKey(body.key);
    if (!safeKey) {
      reply.code(400);
      return { error: 'key must match [a-z0-9][a-z0-9-_]{1,63}' };
    }
    let buf: Buffer;
    try {
      buf = Buffer.from(body.data, 'base64');
    } catch {
      reply.code(400);
      return { error: 'data must be base64' };
    }
    if (buf.length === 0 || buf.length > MAX_AUDIO_BYTES) {
      reply.code(413);
      return { error: `audio size ${buf.length} exceeds ${MAX_AUDIO_BYTES}` };
    }

    const { path, mirroredToDist } = await mirrorAudioToDisk(safeKey, buf);

    // Sibling cleanup: if an old .wav exists at the same key, drop it
    // so reconcileManifestForKey doesn't pick the wrong file.
    for (const dir of [PUBLIC_AUDIO_DIR, DIST_AUDIO_DIR]) {
      try {
        await unlink(join(dir, `${safeKey}.wav`));
      } catch {
        // not there
      }
    }

    // Update the prompt entry's gain (if the admin tweaked it) and
    // reconcile the manifest. reconcileManifestForKey honours the
    // `enabled` flag — saving an audio while the prompt is disabled
    // writes the file but keeps the manifest entry absent so the
    // runtime stays on its synth/procedural fallback.
    const prompts = await readPrompts();
    const stored = prompts[safeKey];
    const merged: AudioPromptEntry = {
      // Fallback shape covers the rare case where an admin clicks Save
      // without ever having configured a prompt entry — keep both the
      // file and a derivable kind so a later toggle has something to
      // operate on.
      prompt: stored?.prompt ?? '',
      kind: stored?.kind ?? (safeKey.startsWith('music-') ? 'music' : 'sfx'),
      ...stored,
      ...(body.gain !== undefined ? { gain: Math.max(0, Math.min(1, body.gain)) } : {}),
    };
    if (!stored || merged.gain !== stored.gain) {
      Object.defineProperty(prompts, safeKey, {
        value: merged,
        writable: true,
        enumerable: true,
        configurable: true,
      });
      await writePrompts(prompts);
    }
    await reconcileManifestForKey(safeKey, merged);
    const manifest = await readManifest();
    const manifestEntry = manifest.find((e) => e.key === safeKey) ?? null;

    return {
      ok: true,
      path,
      size: buf.length,
      mirroredToDist,
      enabled: merged.enabled !== false,
      manifestEntry,
    };
  });

  app.delete('/admin/api/audio/:key', async (req, reply) => {
    const params = req.params as { key: string };
    const safeKey = sanitizeKey(params.key);
    if (!safeKey) {
      reply.code(400);
      return { error: 'invalid key' };
    }
    let removed = 0;
    for (const dir of [PUBLIC_AUDIO_DIR, DIST_AUDIO_DIR]) {
      for (const ext of ['mp3', 'wav']) {
        try {
          await unlink(join(dir, `${safeKey}.${ext}`));
          removed++;
        } catch {
          // not there
        }
      }
    }
    const manifest = await readManifest();
    const next = manifest.filter((e) => e.key !== safeKey);
    if (next.length !== manifest.length) {
      await writeManifest(next);
    }
    return { ok: true, removed };
  });

  app.log.info('admin audio API mounted');
}
