// Admin audio API. Sits next to /admin/api/* sprite routes and shares
// the same bearer-auth hook (registerAdminHook in auth/adminAuth.ts).
//
// The audio pipeline mirrors the sprite one:
//   * Prompts live in tools/audio-gen/audio-prompts.json (committable).
//   * Generated bytes land in client/public/audio/<key>.mp3 (mirrored
//     into client/dist/assets-style if the build dir exists), and the
//     manifest at client/public/audio/manifest.json is rewritten so
//     the runtime audioAssets.ts loader picks them up.
//   * Each entry has a kind ('sfx' | 'music') so the admin UI knows
//     whether to expose a duration knob in seconds (sfx) or
//     milliseconds × scene-length (music).
//
// All write routes are 503 when ELEVENLABS_API_KEY is unset — generate
// would fail anyway and we want a clear error in the UI.

import type { FastifyInstance } from 'fastify';
import { existsSync } from 'node:fs';
import { mkdir, readFile, readdir, stat, writeFile, unlink } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  elevenLabsConfigured,
  generateMusic,
  generateSfx,
} from '../admin/elevenlabs.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..', '..', '..');

const PUBLIC_AUDIO_DIR = join(REPO_ROOT, 'client', 'public', 'audio');
const DIST_AUDIO_DIR = join(REPO_ROOT, 'client', 'dist', 'audio');
const PROMPTS_PATH = join(REPO_ROOT, 'tools', 'audio-gen', 'audio-prompts.json');
const MANIFEST_PATH = join(PUBLIC_AUDIO_DIR, 'manifest.json');

// Keys are short stable identifiers — same shape as sprite keys so the
// validation can stay identical.
const ALLOWED_KEY_RE = /^[a-z0-9][a-z0-9-_]{1,63}$/i;
const DANGEROUS_KEYS = new Set(['__proto__', 'prototype', 'constructor']);
const MAX_PROMPT_BYTES = 4096;
const MAX_AUDIO_BYTES = 15 * 1024 * 1024; // 15 MB — well above any 5-minute mp3.

function sanitizeKey(key: string): string | null {
  if (DANGEROUS_KEYS.has(key)) return null;
  return ALLOWED_KEY_RE.test(key) ? key : null;
}

export type AudioKind = 'sfx' | 'music';

interface AudioPromptEntry {
  // Free-text prompt sent to ElevenLabs. Trimmed; up to MAX_PROMPT_BYTES.
  prompt: string;
  // Categorises the entry — controls which ElevenLabs endpoint we hit
  // and which duration knob the admin UI shows.
  kind: AudioKind;
  // Optional seconds (sfx) — clamped 0.5..22 server-side.
  durationSeconds?: number;
  // Optional milliseconds (music) — clamped 10000..300000 server-side.
  durationMs?: number;
  // Optional 0..1, sfx-only. Higher = stricter prompt adherence.
  promptInfluence?: number;
  // Optional 0..1 master gain applied at playback time. Mirrors the
  // sprite manifest's `gain` field; defaults to 0.7 in audioAssets.ts.
  gain?: number;
  // Free-text label shown in the admin UI. Useful when one key has
  // several "moods" tracked over time.
  label?: string;
}

type AudioPromptsFile = Record<string, AudioPromptEntry>;

async function readPrompts(): Promise<AudioPromptsFile> {
  try {
    const raw = await readFile(PROMPTS_PATH, 'utf8');
    const parsed = JSON.parse(raw) as unknown;
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      // Strip any prototype-pollution attempts from the on-disk file.
      const out: AudioPromptsFile = Object.create(null) as AudioPromptsFile;
      for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
        if (DANGEROUS_KEYS.has(k)) continue;
        if (!ALLOWED_KEY_RE.test(k)) continue;
        if (!v || typeof v !== 'object') continue;
        const e = v as Partial<AudioPromptEntry>;
        if (typeof e.prompt !== 'string') continue;
        if (e.kind !== 'sfx' && e.kind !== 'music') continue;
        out[k] = {
          prompt: e.prompt,
          kind: e.kind,
          ...(typeof e.durationSeconds === 'number' && { durationSeconds: e.durationSeconds }),
          ...(typeof e.durationMs === 'number' && { durationMs: e.durationMs }),
          ...(typeof e.promptInfluence === 'number' && { promptInfluence: e.promptInfluence }),
          ...(typeof e.gain === 'number' && { gain: e.gain }),
          ...(typeof e.label === 'string' && { label: e.label }),
        };
      }
      return out;
    }
  } catch {
    // missing / malformed → start from empty so the admin UI still loads
  }
  return Object.create(null) as AudioPromptsFile;
}

async function writePrompts(prompts: AudioPromptsFile): Promise<void> {
  await mkdir(dirname(PROMPTS_PATH), { recursive: true });
  await writeFile(PROMPTS_PATH, JSON.stringify(prompts, null, 2) + '\n', 'utf8');
}

interface ManifestEntry {
  key: string;
  src: string;
  gain?: number;
}

async function readManifest(): Promise<ManifestEntry[]> {
  try {
    const raw = await readFile(MANIFEST_PATH, 'utf8');
    const parsed = JSON.parse(raw) as unknown;
    if (Array.isArray(parsed)) {
      return parsed.filter(
        (e): e is ManifestEntry =>
          !!e &&
          typeof e === 'object' &&
          typeof (e as ManifestEntry).key === 'string' &&
          typeof (e as ManifestEntry).src === 'string',
      );
    }
  } catch {
    // missing → empty
  }
  return [];
}

async function writeManifest(entries: ManifestEntry[]): Promise<void> {
  await mkdir(PUBLIC_AUDIO_DIR, { recursive: true });
  await writeFile(MANIFEST_PATH, JSON.stringify(entries, null, 2) + '\n', 'utf8');
}

async function mirrorAudioToDisk(
  key: string,
  bytes: Buffer,
): Promise<{ path: string; mirroredToDist: boolean }> {
  const filename = `${key}.mp3`;
  await mkdir(PUBLIC_AUDIO_DIR, { recursive: true });
  await writeFile(join(PUBLIC_AUDIO_DIR, filename), bytes);
  let mirroredToDist = false;
  if (existsSync(join(REPO_ROOT, 'client', 'dist'))) {
    try {
      await mkdir(DIST_AUDIO_DIR, { recursive: true });
      await writeFile(join(DIST_AUDIO_DIR, filename), bytes);
      mirroredToDist = true;
    } catch {
      // best-effort
    }
  }
  return { path: `/audio/${filename}`, mirroredToDist };
}

interface FileMeta {
  key: string;
  filename: string;
  size: number;
  mtime: number;
}

async function listAudioFiles(): Promise<FileMeta[]> {
  const out: FileMeta[] = [];
  try {
    const names = await readdir(PUBLIC_AUDIO_DIR);
    for (const n of names) {
      if (!n.endsWith('.mp3') && !n.endsWith('.wav')) continue;
      try {
        const s = await stat(join(PUBLIC_AUDIO_DIR, n));
        const key = n.replace(/\.(mp3|wav)$/i, '');
        out.push({ key, filename: n, size: s.size, mtime: s.mtimeMs });
      } catch {
        // file disappeared mid-listing
      }
    }
  } catch {
    // dir doesn't exist yet
  }
  return out;
}

interface UpsertPromptBody {
  key: string;
  entry: AudioPromptEntry;
}

interface GenerateBody {
  key: string;
  // Override the on-disk prompt for a single ad-hoc generation. If omitted
  // the server reads the prompt from audio-prompts.json[key].
  prompt?: string;
  kind?: AudioKind;
  durationSeconds?: number;
  durationMs?: number;
  promptInfluence?: number;
}

interface SaveBody {
  key: string;
  data: string; // base64 mp3
  // Optional gain override stored in the manifest. Defaults to whatever
  // is set on the prompt entry, falling back to 0.7 at runtime.
  gain?: number;
}

export function registerAdminAudio(app: FastifyInstance): void {
  // Combined status: prompt config, on-disk files, manifest, and the
  // ElevenLabs configuration flag so the UI can show a banner when the
  // key is missing.
  app.get('/admin/api/audio/status', async () => {
    const [prompts, files, manifest] = await Promise.all([
      readPrompts(),
      listAudioFiles(),
      readManifest(),
    ]);
    return {
      elevenLabsConfigured: elevenLabsConfigured(),
      audioDir: PUBLIC_AUDIO_DIR,
      prompts,
      files,
      manifest,
    };
  });

  app.put<{ Body: UpsertPromptBody }>(
    '/admin/api/audio/prompts',
    async (req, reply) => {
      const body = req.body;
      if (!body || typeof body.key !== 'string' || !body.entry) {
        reply.code(400);
        return { error: 'key + entry required' };
      }
      const safeKey = sanitizeKey(body.key);
      if (!safeKey) {
        reply.code(400);
        return { error: 'key must match [a-z0-9][a-z0-9-_]{1,63}' };
      }
      const e = body.entry;
      if (typeof e.prompt !== 'string' || e.prompt.length > MAX_PROMPT_BYTES) {
        reply.code(400);
        return { error: `prompt required, ≤${MAX_PROMPT_BYTES} chars` };
      }
      if (e.kind !== 'sfx' && e.kind !== 'music') {
        reply.code(400);
        return { error: 'kind must be "sfx" or "music"' };
      }
      const sanitized: AudioPromptEntry = {
        prompt: e.prompt,
        kind: e.kind,
      };
      if (typeof e.durationSeconds === 'number' && Number.isFinite(e.durationSeconds)) {
        sanitized.durationSeconds = Math.max(0.5, Math.min(22, e.durationSeconds));
      }
      if (typeof e.durationMs === 'number' && Number.isFinite(e.durationMs)) {
        sanitized.durationMs = Math.max(10000, Math.min(300000, Math.floor(e.durationMs)));
      }
      if (typeof e.promptInfluence === 'number' && Number.isFinite(e.promptInfluence)) {
        sanitized.promptInfluence = Math.max(0, Math.min(1, e.promptInfluence));
      }
      if (typeof e.gain === 'number' && Number.isFinite(e.gain)) {
        sanitized.gain = Math.max(0, Math.min(1, e.gain));
      }
      if (typeof e.label === 'string' && e.label.trim() !== '') {
        sanitized.label = e.label.trim().slice(0, 120);
      }

      const prompts = await readPrompts();
      // Object.defineProperty avoids __proto__ shenanigans even though
      // the key has already passed the regex.
      Object.defineProperty(prompts, safeKey, {
        value: sanitized,
        writable: true,
        enumerable: true,
        configurable: true,
      });
      await writePrompts(prompts);
      return { ok: true, key: safeKey, entry: sanitized };
    },
  );

  app.delete('/admin/api/audio/prompts/:key', async (req, reply) => {
    const params = req.params as { key: string };
    const safeKey = sanitizeKey(params.key);
    if (!safeKey) {
      reply.code(400);
      return { error: 'invalid key' };
    }
    const prompts = await readPrompts();
    if (!Object.prototype.hasOwnProperty.call(prompts, safeKey)) {
      return { ok: true, removed: false };
    }
    delete prompts[safeKey];
    await writePrompts(prompts);
    return { ok: true, removed: true };
  });

  app.post<{ Body: GenerateBody }>(
    '/admin/api/audio/generate',
    async (req, reply) => {
      const body = req.body;
      if (!body || typeof body.key !== 'string') {
        reply.code(400);
        return { error: 'key required' };
      }
      const safeKey = sanitizeKey(body.key);
      if (!safeKey) {
        reply.code(400);
        return { error: 'key must match [a-z0-9][a-z0-9-_]{1,63}' };
      }
      const prompts = await readPrompts();
      const stored = prompts[safeKey];
      const prompt = (body.prompt ?? stored?.prompt ?? '').trim();
      const kind: AudioKind =
        body.kind ?? stored?.kind ?? (safeKey.startsWith('music-') ? 'music' : 'sfx');
      if (prompt === '') {
        reply.code(400);
        return { error: 'prompt required (set one in the admin UI or pass it inline)' };
      }
      try {
        let audio;
        if (kind === 'music') {
          audio = await generateMusic({
            prompt,
            ...(body.durationMs !== undefined
              ? { durationMs: body.durationMs }
              : stored?.durationMs !== undefined
                ? { durationMs: stored.durationMs }
                : {}),
          });
        } else {
          audio = await generateSfx({
            prompt,
            ...(body.durationSeconds !== undefined
              ? { durationSeconds: body.durationSeconds }
              : stored?.durationSeconds !== undefined
                ? { durationSeconds: stored.durationSeconds }
                : {}),
            ...(body.promptInfluence !== undefined
              ? { promptInfluence: body.promptInfluence }
              : stored?.promptInfluence !== undefined
                ? { promptInfluence: stored.promptInfluence }
                : {}),
          });
        }
        return { audio, kind, key: safeKey };
      } catch (err) {
        reply.code(502);
        return { error: (err as Error).message };
      }
    },
  );

  app.post<{ Body: SaveBody }>('/admin/api/audio/save', async (req, reply) => {
    const body = req.body;
    if (!body || !body.key || !body.data) {
      reply.code(400);
      return { error: 'key + data required' };
    }
    const safeKey = sanitizeKey(body.key);
    if (!safeKey) {
      reply.code(400);
      return { error: 'key must match [a-z0-9][a-z0-9-_]{1,63}' };
    }
    let buf: Buffer;
    try {
      buf = Buffer.from(body.data, 'base64');
    } catch {
      reply.code(400);
      return { error: 'data must be base64' };
    }
    if (buf.length === 0 || buf.length > MAX_AUDIO_BYTES) {
      reply.code(413);
      return { error: `audio size ${buf.length} exceeds ${MAX_AUDIO_BYTES}` };
    }

    const { path, mirroredToDist } = await mirrorAudioToDisk(safeKey, buf);

    // Update manifest in place so the runtime loader picks the new
    // sample up on the next page load. Existing entry replaced; new
    // one appended. Old .wav siblings (if a key was previously
    // synth-generated) are unlinked so the manifest doesn't point at
    // both formats.
    const prompts = await readPrompts();
    const stored = prompts[safeKey];
    const gain = body.gain ?? stored?.gain;
    const manifest = await readManifest();
    const idx = manifest.findIndex((e) => e.key === safeKey);
    const next: ManifestEntry = {
      key: safeKey,
      src: `${safeKey}.mp3`,
      ...(typeof gain === 'number' ? { gain } : {}),
    };
    if (idx >= 0) manifest[idx] = next;
    else manifest.push(next);
    await writeManifest(manifest);

    // Sibling cleanup: if an old .wav exists at the same key, drop it
    // so the manifest's mp3 entry isn't shadowed on disk.
    for (const dir of [PUBLIC_AUDIO_DIR, DIST_AUDIO_DIR]) {
      try {
        await unlink(join(dir, `${safeKey}.wav`));
      } catch {
        // not there
      }
    }

    return {
      ok: true,
      path,
      size: buf.length,
      mirroredToDist,
      manifestEntry: next,
    };
  });

  app.delete('/admin/api/audio/:key', async (req, reply) => {
    const params = req.params as { key: string };
    const safeKey = sanitizeKey(params.key);
    if (!safeKey) {
      reply.code(400);
      return { error: 'invalid key' };
    }
    let removed = 0;
    for (const dir of [PUBLIC_AUDIO_DIR, DIST_AUDIO_DIR]) {
      for (const ext of ['mp3', 'wav']) {
        try {
          await unlink(join(dir, `${safeKey}.${ext}`));
          removed++;
        } catch {
          // not there
        }
      }
    }
    const manifest = await readManifest();
    const next = manifest.filter((e) => e.key !== safeKey);
    if (next.length !== manifest.length) {
      await writeManifest(next);
    }
    return { ok: true, removed };
  });

  app.log.info('admin audio API mounted');
}
